import {build} from "esbuild"
import {promises as fs} from "node:fs"
import path from "node:path"

const outputDir = path.resolve("../leptos-tiptap/src/js/generated")
const extensionsDir = path.resolve("./src/extensions")
const bridgeGlobalKey = "__LEPTOS_TIPTAP_BRIDGE__"
const hostedModulesSourcePath = path.resolve("./src/generated/hosted_modules.ts")

// Keep the shared runtime optimized for the common/default extension set.
const SHARED_BASE_MODULES = [
    "@tiptap/core",
    "@tiptap/pm/commands",
    "@tiptap/pm/dropcursor",
    "@tiptap/pm/gapcursor",
    "@tiptap/pm/history",
    "@tiptap/pm/keymap",
    "@tiptap/pm/model",
    "@tiptap/pm/schema-list",
    "@tiptap/pm/state",
    "@tiptap/pm/transform",
    "@tiptap/pm/view",
]

const bridgeRuntimeEntry = {
    bridge_runtime: "./src/bridge_runtime.ts",
}

const exportNameCache = new Map()

function createHostedModulePlugin(hostedModuleNames) {
    const hostedModules = new Set(hostedModuleNames)

    return {
        name: "hosted-modules",
        setup(pluginBuild) {
            pluginBuild.onResolve({
                filter: /.*/,
            }, (args) => {
                if (!hostedModules.has(args.path)) {
                    return null
                }

                return {
                    path: args.path,
                    namespace: "hosted-module",
                }
            })

            pluginBuild.onLoad({filter: /.*/, namespace: "hosted-module"}, async (args) => ({
                contents: await createHostedModuleContents(args.path),
                loader: "js",
            }))
        },
    }
}

async function createHostedModuleContents(moduleName) {
    let exportNames = exportNameCache.get(moduleName)
    if (exportNames == null) {
        const namespace = await import(moduleName)
        exportNames = Object.keys(namespace)
            .filter((name) => name !== "default")
            .sort()
        exportNameCache.set(moduleName, exportNames)
    }

    const lines = [
        `const bridgeBindings = globalThis.${bridgeGlobalKey};`,
        "if (bridgeBindings == null || bridgeBindings.modules == null) throw new Error(\"leptos-tiptap bridge bindings are unavailable\");",
        `const moduleExports = bridgeBindings.modules[${JSON.stringify(moduleName)}];`,
        `if (moduleExports == null) throw new Error(${JSON.stringify(`leptos-tiptap bridge module "${moduleName}" is unavailable`)});`,
    ]

    for (const exportName of exportNames) {
        lines.push(`export const ${exportName} = moduleExports[${JSON.stringify(exportName)}];`)
    }

    return lines.join("\n")
}

async function discoverExtensionEntries() {
    const files = (await fs.readdir(extensionsDir))
        .filter((name) => name.startsWith("tiptap_") && name.endsWith(".ts"))
        .sort()

    return Object.fromEntries(
        files.map((name) => [
            path.basename(name, ".ts"),
            `./src/extensions/${name}`,
        ]),
    )
}

function moduleIdentifier(moduleName) {
    const normalizedName = moduleName.replace(/^@/, "")
    const segments = normalizedName.split(/[/-]/).filter(Boolean)
    return `hosted${segments.map((segment) => segment[0].toUpperCase() + segment.slice(1)).join("")}`
}

function createHostedModulesSource(moduleNames) {
    const imports = moduleNames
        .map((moduleName) => `import * as ${moduleIdentifier(moduleName)} from ${JSON.stringify(moduleName)}`)
        .join("\n")

    const entries = moduleNames
        .map((moduleName) => `    ${JSON.stringify(moduleName)}: ${moduleIdentifier(moduleName)},`)
        .join("\n")

    const names = moduleNames
        .map((moduleName) => `    ${JSON.stringify(moduleName)},`)
        .join("\n")

    return `// This file is generated by build.mjs. Do not edit manually.

${imports}

const hostedModules: Record<string, unknown> = {
${entries}
}

export const HOSTED_MODULE_NAMES = [
${names}
] as const

export function installHostedModules(modules: Record<string, unknown>): void {
    Object.assign(modules, hostedModules)
}
`
}

async function writeHostedModulesSource(moduleNames) {
    await fs.mkdir(path.dirname(hostedModulesSourcePath), {recursive: true})
    await fs.writeFile(hostedModulesSourcePath, createHostedModulesSource(moduleNames))
}

async function validateImportFreeArtifacts(directory) {
    const files = (await fs.readdir(directory))
        .filter((name) => name.endsWith(".js"))

    for (const file of files) {
        const contents = await fs.readFile(path.join(directory, file), "utf8")
        if (/^\s*import\s/m.test(contents)) {
            throw new Error(`Generated artifact ${file} still contains an import statement.`)
        }
    }
}

async function buildEntryPoints(entryPoints, plugins = []) {
    await build({
        entryPoints,
        bundle: true,
        format: "esm",
        minify: true,
        platform: "browser",
        splitting: false,
        target: "es2020",
        outdir: outputDir,
        plugins,
    })
}

await fs.rm(outputDir, {recursive: true, force: true})
await fs.mkdir(outputDir, {recursive: true})

const extensionEntries = await discoverExtensionEntries()
await writeHostedModulesSource(SHARED_BASE_MODULES)

await buildEntryPoints(bridgeRuntimeEntry)

const hostedModulePlugin = createHostedModulePlugin(SHARED_BASE_MODULES)

for (const [outfile, entryPoint] of Object.entries(extensionEntries)) {
    await buildEntryPoints({[outfile]: entryPoint}, [hostedModulePlugin])
}

await validateImportFreeArtifacts(outputDir)
