// Bundles the TypeScript bridge into import-free wasm-bindgen snippets and records their licenses.
// The Rust crate ships these generated artifacts, so both outputs must be rebuilt together.

import {build} from "esbuild"
import {promises as fs} from "node:fs"
import path from "node:path"
import {fileURLToPath} from "node:url"

import {BRIDGE_GLOBAL_KEY} from "./bridge-config.mjs"
import {writeThirdPartyNotices} from "./third-party-notices.mjs"

const moduleDirectory = path.dirname(fileURLToPath(import.meta.url))
const outputDir = path.resolve(moduleDirectory, "../src/js/generated")
const extensionsDir = path.resolve(moduleDirectory, "./src/extensions")
const hostedModulesSourcePath = path.resolve(moduleDirectory, "./src/generated/hosted_modules.ts")

// Keep the shared runtime optimized for the common/default extension set.
const SHARED_BASE_MODULES = [
    "@tiptap/core",
    "@tiptap/pm/commands",
    "@tiptap/pm/dropcursor",
    "@tiptap/pm/gapcursor",
    "@tiptap/pm/history",
    "@tiptap/pm/keymap",
    "@tiptap/pm/model",
    "@tiptap/pm/schema-list",
    "@tiptap/pm/state",
    "@tiptap/pm/transform",
    "@tiptap/pm/view",
]

const bridgeRuntimeEntry = {
    bridge_runtime: "./src/bridge_runtime.ts",
}

/** @type {Map<string, string[]>} */
const exportNameCache = new Map()

/**
 * @param {string[]} hostedModuleNames
 * @returns {import("esbuild").Plugin}
 */
function createHostedModulePlugin(hostedModuleNames) {
    const hostedModules = new Set(hostedModuleNames)

    return {
        name: "hosted-modules",
        setup(pluginBuild) {
            pluginBuild.onResolve({
                filter: /.*/,
            }, (args) => {
                if (!hostedModules.has(args.path)) {
                    return null
                }

                return {
                    path: args.path,
                    namespace: "hosted-module",
                }
            })

            pluginBuild.onLoad({filter: /.*/, namespace: "hosted-module"}, async (args) => ({
                contents: await createHostedModuleContents(args.path),
                loader: "js",
            }))
        },
    }
}

/** @param {string} moduleName */
async function createHostedModuleContents(moduleName) {
    let exportNames = exportNameCache.get(moduleName)
    if (exportNames == null) {
        const namespace = await import(moduleName)
        exportNames = Object.keys(namespace)
            .filter((name) => name !== "default")
            .sort()
        exportNameCache.set(moduleName, exportNames)
    }

    const lines = [
        `const bridgeHost = globalThis[${JSON.stringify(BRIDGE_GLOBAL_KEY)}];`,
        "const bridgeBindings = bridgeHost?.getBindings(new URL(\".\", import.meta.url).href);",
        "if (bridgeBindings == null || bridgeBindings.modules == null) throw new Error(\"leptos-tiptap bridge bindings are unavailable\");",
        `const moduleExports = bridgeBindings.modules[${JSON.stringify(moduleName)}];`,
        `if (moduleExports == null) throw new Error(${JSON.stringify(`leptos-tiptap bridge module "${moduleName}" is unavailable`)});`,
    ]

    for (const exportName of exportNames) {
        lines.push(`export const ${exportName} = moduleExports[${JSON.stringify(exportName)}];`)
    }

    return lines.join("\n")
}

/** @returns {Promise<Record<string, string>>} */
async function discoverExtensionEntries() {
    const files = (await fs.readdir(extensionsDir))
        .filter((name) => name.startsWith("tiptap_") && name.endsWith(".ts"))
        .sort()

    return Object.fromEntries(
        files.map((name) => [
            path.basename(name, ".ts"),
            `./src/extensions/${name}`,
        ]),
    )
}

/** @param {string} moduleName */
function moduleIdentifier(moduleName) {
    const normalizedName = moduleName.replace(/^@/, "")
    const segments = normalizedName.split(/[/-]/).filter(Boolean)
    return `hosted${segments.map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1)).join("")}`
}

/** @param {string[]} moduleNames */
function createHostedModulesSource(moduleNames) {
    const imports = moduleNames
        .map((moduleName) => `import * as ${moduleIdentifier(moduleName)} from ${JSON.stringify(moduleName)}`)
        .join("\n")

    const entries = moduleNames
        .map((moduleName) => `    ${JSON.stringify(moduleName)}: ${moduleIdentifier(moduleName)},`)
        .join("\n")

    const names = moduleNames
        .map((moduleName) => `    ${JSON.stringify(moduleName)},`)
        .join("\n")

    return `// This file is generated by build.mjs. Do not edit manually.

${imports}

const hostedModules: Record<string, unknown> = {
${entries}
}

export const HOSTED_MODULE_NAMES = [
${names}
] as const

export function installHostedModules(modules: Record<string, unknown>): void {
    Object.assign(modules, hostedModules)
}
`
}

/** @param {string[]} moduleNames */
async function writeHostedModulesSource(moduleNames) {
    await fs.mkdir(path.dirname(hostedModulesSourcePath), {recursive: true})
    await fs.writeFile(hostedModulesSourcePath, createHostedModulesSource(moduleNames))
}

/** @param {string} directory */
async function validateImportFreeArtifacts(directory) {
    const files = (await fs.readdir(directory))
        .filter((name) => name.endsWith(".js"))

    for (const file of files) {
        const contents = await fs.readFile(path.join(directory, file), "utf8")
        if (/^\s*import\s/m.test(contents)) {
            throw new Error(`Generated artifact ${file} still contains an import statement.`)
        }
    }
}

/**
 * @param {Record<string, string>} entryPoints
 * @param {import("esbuild").Plugin[]} plugins
 */
async function buildEntryPoints(entryPoints, plugins = []) {
    const result = await build({
        absWorkingDir: moduleDirectory,
        entryPoints,
        bundle: true,
        format: "esm",
        metafile: true,
        minify: true,
        platform: "browser",
        splitting: false,
        target: "es2022",
        outdir: outputDir,
        plugins,
    })
    return result.metafile
}

await fs.rm(outputDir, {recursive: true, force: true})
await fs.mkdir(outputDir, {recursive: true})

const extensionEntries = await discoverExtensionEntries()
await writeHostedModulesSource(SHARED_BASE_MODULES)

const metafiles = [await buildEntryPoints(bridgeRuntimeEntry)]

const hostedModulePlugin = createHostedModulePlugin(SHARED_BASE_MODULES)

metafiles.push(await buildEntryPoints(extensionEntries, [hostedModulePlugin]))

await validateImportFreeArtifacts(outputDir)
await writeThirdPartyNotices(metafiles, {workingDirectory: moduleDirectory})
