var TipTap = require('@tiptap/core')
var TipTapStarterKit = require('@tiptap/starter-kit')
var TipTapHighlight = require('@tiptap/extension-highlight')
var TipTapTextAlign = require('@tiptap/extension-text-align')
var TipTapImage = require('@tiptap/extension-image')
var TipTapLink = require('@tiptap/extension-link')
var TipTapYoutube = require('@tiptap/extension-youtube')
global.window.TipTap = TipTap
global.window.TipTapStarterKit = TipTapStarterKit
global.window.TipTapHighlight = TipTapHighlight
global.window.TipTapTextAlign = TipTapTextAlign
global.window.TipTapImage = TipTapImage
global.window.TipTapLink = TipTapLink
global.window.TipTapYoutube = TipTapYoutube
